services:
  jupyter:
    build: .
    volumes:
      - type: bind
        source: ./code
        target: /home/code
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
     - metadb_network
  metadata_db:
    image: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_DB: pg
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - metadb_network

volumes:
  postgres-data:

networks:
  metadb_network:
    driver: bridge